version: '3'
services:
  db:
    image: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: react-site
    volumes:
      - postgre
    networks:
      - app

volumes:
  postgre:

networks:
  app: