version: '3'
services:
  db:
    image: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: react-site
    volumes:
      - postgre
    networks:
      - app
  
  api:
    build: .
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - db
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: react-site
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - app

volumes:
  postgre:

networks:
  app: